version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      next-react:
        patterns:
          - next
          - react
          - react-dom
          - eslint-config-next
      tooling:
        dependency-type: development
